#!/bin/sh

mkdir -p ~/.blameyourisp
log=~/.blameyourisp/blameyourisp.log
SLEEP=15 # minutes
isp_url="http://ip-api.com/line"

function isp {
    out=`wget $isp_url -O- 2>/dev/null`
    _isp=`echo "$out" | sed '11q;d'`
    _city=`echo "$out" | sed '10q;d'`
    _zip=`echo "$out" | sed '7q;d'`

    echo "ISP: $_isp ($_city, $_zip)"
}

while [ 1 ]; do
    date -Iminutes | tee -a $log
    isp | tee -a $log
    (speedtest-cli --simple | tee -a $log && blameyourisp-graph) &
    sleep "$SLEEP"m
done

